pyubcg:
  image: python:3.6
  when: always
  allow_failure: no
  script:
    - apt-get update -q -y
    - apt-get install -y python3-dev python3-setuptools
    - pip3 install virtualenv
    - chmod +x install_venv.sh
    - ./install_venv.sh
    - ./venv.sh
