FROM openjdk:8u181-jre

RUN apt update -y
RUN apt upgrade -y
RUN apt-get install -y build-essential  git wget unzip jq vim
RUN git clone https://github.com/stamatak/standard-RAxML.git && cd standard-RAxML \
    && make -f Makefile.gcc && rm *.o && make -f Makefile.SSE3.gcc && rm *.o \
    && make -f Makefile.PTHREADS.gcc && rm *.o && make -f Makefile.SSE3.PTHREADS.gcc \
    && cp raxmlHPC* /usr/bin/
RUN apt install -y hmmer
RUN git clone https://github.com/hyattpd/Prodigal.git && cd Prodigal && make install
RUN wget http://www.microbesonline.org/fasttree/FastTree.c && \
    gcc -DNO_SSE -O3 -finline-functions -funroll-loops -Wall -o FastTree FastTree.c -lm && mv FastTree /usr/local/bin

RUN wget https://mafft.cbrc.jp/alignment/software/mafft_7.407-1_amd64.deb && dpkg -i mafft_7.407-1_amd64.deb

#RUN apt-get update -q -y && \
#     apt-get install -y python3-dev python3-setuptools && \
#     pip3 install virtualenv
WORKDIR /UBCG
COPY ./UBCG /UBCG
COPY ./extract_output /UBCG/extract_output

#RUN chmod +x install_venv.sh && ./install_venv.sh
#RUN make install_dep








RUN java -jar UBCG.jar extract -bcg_dir bcg -i fasta/CP012646_s_GCA_001281025.1_KCOM_1350.fasta -label "CP012646_s KCOM 1350" -acc "GCA_001281025.1" -taxon "CP012646_s" -strain "KCOM 1350" && \
    \
    java -jar UBCG.jar extract -bcg_dir bcg -i fasta/Streptococcus_constellatus_subsp._constellatus_GCA_000474075.1_SK53_TYPE.fasta -label "Streptococcus constellatus subsp. constellatus SK53(T)" -acc "GCA_000474075.1" -taxon "Streptococcus constellatus subsp. constellatus" -strain "SK53" -type  && \
    \
    java -jar UBCG.jar extract -bcg_dir bcg -i fasta/Streptococcus_constellatus_subsp._pharyngis_GCA_000223295.2_SK1060_TYPE.fasta -label "Streptococcus constellatus subsp. pharyngis SK1060(T)" -acc "GCA_000223295.2" -taxon "Streptococcus constellatus subsp. pharyngis" -strain "SK1060" -type && \
    \
    java -jar UBCG.jar extract -bcg_dir bcg -i fasta/CP014326_s_GCA_001560895.1_SVGS_061.fasta -label "CP014326_s SVGS_061" -acc "GCA_001560895.1" -taxon "CP014326_s" -strain "SVGS_061" && \
    \
    java -jar UBCG.jar extract -bcg_dir bcg -i fasta/Streptococcus_mitis_GCA_002014755.1_CCUG_31611_TYPE.fasta -label "Streptococcus mitis CCUG 31611(T)" -acc "GCA_002014755.1" -taxon "Streptococcus mitis" -strain "CCUG 31611" -type && \
    \
    java -jar UBCG.jar extract -bcg_dir bcg -i fasta/Streptococcus_pneumoniae_GCA_001457635.1_NCTC_7465_TYPE.fasta -label "Streptococcus pneumoniae NCTC 7465(T)" -acc "GCA_001457635.1" -taxon "Streptococcus pneumoniae" -strain "NCTC 7465" -type && \
     \
    java -jar UBCG.jar extract -bcg_dir bcg -i fasta/Streptococcus_pseudopneumoniae_GCA_002087075.1_CCUG_49455_TYPE.fasta -label "Streptococcus pseudopneumoniae CCUG 49455(T)" -acc "GCA_002087075.1" -taxon "Streptococcus pseudopneumoniae" -strain "CCUG 49455" -type && \
    \
    java -jar UBCG.jar extract -bcg_dir bcg -i fasta/Streptococcus_pneumoniae_GCA_000006885.1_TIGR4.fasta -label "Streptococcus pneumoniae TIGR4" -acc "GCA_000006885.1" -taxon "Streptococcus pneumoniae" -strain "TIGR4"

RUN java -jar UBCG.jar align -a nt -bcg_dir bcg -prefix test_nt
RUN java -jar UBCG.jar align -a aa -bcg_dir bcg -prefix test_aa
RUN java -jar UBCG.jar align -a codon12 -bcg_dir bcg -prefix test_codon12
RUN java -jar UBCG.jar align -a codon -bcg_dir bcg -prefix test_codon


RUN java -jar UBCG.jar align -a nt -bcg_dir extract_output -prefix test_nt_pybcg
RUN java -jar UBCG.jar align -a aa -bcg_dir extract_output -prefix test_aa_pybcg
RUN java -jar UBCG.jar align -a codon12 -bcg_dir extract_output -prefix test_codon12_pybcg
RUN java -jar UBCG.jar align -a codon -bcg_dir extract_output -prefix test_codon_pybcg

