project_name: PyUBCG
project_folder: PyUBCG
config: config/config.yaml
fasta_input_folder: fasta_input
prodigal_like_tool: prodigal
output_folder: extract_output
hmmsearch_like_tool: hmmsearch
prodigal_output: prodigal_output
prodigal_translation_table: 11
ubcg_gene: ["alaS", "argS", "aspS", "cgtA", "coaE", "cysS", "dnaA", "dnaG", "dnaX", "engA", "ffh", "fmt", "frr", "ftsY", "gmk", "hisS", "ileS", "infB", "infC", "ksgA", "lepA", "leuS", "ligA", "nusA", "nusG", "pgk", "pheS", "pheT", "prfA", "pyrG", "recA", "rbfA", "rnc", "rplA", "rplB", "rplC", "rplD", "rplE", "rplF", "rplI", "rplJ", "rplK", "rplL", "rplM", "rplN", "rplO", "rplP", "rplQ", "rplR", "rplS", "rplT", "rplU", "rplV", "rplW", "rplX", "rpmA", "rpmC", "rpmI", "rpoA", "rpoB", "rpoC", "rpsB", "rpsC", "rpsD", "rpsE", "rpsF", "rpsG", "rpsH", "rpsI", "rpsJ", "rpsK", "rpsL", "rpsM", "rpsO", "rpsP", "rpsQ", "rpsR", "rpsS", "rpsT", "secA", "secG", "secY", "serS", "smpB", "tig", "tilS", "truB", "tsaD", "tsf", "uvrB", "ybeY", "ychF" ]
hmmsearch_output: hmmsearch_output
hmm_base: UBCG.hmm
nuc_prefix: gene_nuc
pro_prefix: gene_pro
